name: vcse_env
channels:
  - anaconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - contourpy=1.2.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.6.4
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - importlib_resources=6.4.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libabseil=20240116.2
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.11.1
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=12.4.0
  - libgcc-ng=12.4.0
  - libglib=2.78.4
  - libgomp=12.4.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - libssh2=1.11.1
  - libstdcxx=12.4.0
  - libstdcxx-ng=12.4.0
  - libuuid=1.41.5
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mysql=8.4.0
  - ncurses=6.4
  - nspr=4.35
  - nss=3.89.1
  - openldap=2.6.4
  - openssl=3.3.1
  - pcre2=10.42
  - ply=3.11
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - qt=5.15.9
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - readline=8.2
  - sip=6.7.12
  - sqlite=3.45.3
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - tzdata=2025a
  - unicodedata2=15.1.0
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - annotated-types==0.7.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==1.6.0
      - docker-pycreds==0.4.0
      - eval-type-backport==0.2.2
      - farama-notifications==0.0.4
      - filelock==3.17.0
      - fsspec==2024.12.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.70.0
      - gym==0.18.3
      - gymnasium==1.0.0
      - idna==3.10
      - imageio==2.9.0
      - importlib-metadata==8.6.1
      - jinja2==3.1.5
      - markdown==3.7
      - markupsafe==3.0.2
      - minigrid==3.0.0
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python-headless==4.11.0.86
      - packaging==24.2
      - pillow==8.2.0
      - pip==23.0
      - platformdirs==4.3.6
      - protobuf==5.29.3
      - psutil==6.1.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygame==2.6.1
      - pyglet==1.5.15
      - pywavelets==1.6.0
      - pyyaml==6.0.2
      - requests==2.32.3
      - scikit-image==0.19.3
      - scipy==1.13.1
      - sentry-sdk==2.20.0
      - setproctitle==1.3.4
      - setuptools==57.5.0
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tifffile==2024.8.30
      - torch==2.5.1
      - triton==3.1.0
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - wandb==0.19.4
      - werkzeug==3.1.3
      - zipp==3.21.0
